logPath: '<%= @log_file %>'
httpServer:
  port: <%= @http_server_port %>
  apiKey: '<%= @http_server_api_key %>'
webSocketServer:
  port: <%= @websockets_listen_port %>
janus:
  webSocketAddress: '<%= @janus_websocket_address %>'
  httpAddress: '<%= @janus_http_address %>'
cmApi:
  baseUrl: '<%= @cm_api_base_url %>'
  apiKey:  '<%= @cm_api_key %>'
cmApplication:
  path: '<%= @cm_application_path %>'
jobManager:
  jobsPath: '<%= @jobs_path %>'
  tempFilesPath: '<%= @job_temp_dir %>'
  handlersConfiguration:
    'janus.plugin.cm.audioroom:archive-finished':
      convertCommand: '<%= @job_prefix %> lame <%%= wavFile %> <%%= mp3File %>'
    'janus.plugin.cm.rtpbroadcast:archive-finished':
      mergeCommand: '<%= @job_prefix %> mjr2webm <%%= videoMjrFile %> <%%= audioMjrFile %> <%%= webmFile %>'
    'janus.plugin.cm.rtpbroadcast:thumbnailing-finished':
      createThumbnailCommand: '<%= @job_prefix %> mjr2png <%%= videoMjrFile %> <%= @thumbnailWidth %> <%= @thumbnailHeight %> <%%= pngFile %>'

